language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

# lock distro so new future defaults will not break the build
dist: precise

# also test against HHVM, but require "trusty" and ignore errors
matrix:
  include:
    - php: hhvm
      dist: trusty
  allow_failures:
    - php: hhvm

env:
  - LOGIN=username:password@localhost

install:
  - sudo apt-get -qq update && sudo apt-get --no-install-recommends -qq install -y asterisk
  - sudo cp tests/username.conf /etc/asterisk/manager.d/username.conf
  - sudo /etc/init.d/asterisk reload
  - composer install --prefer-source --no-interaction

script:
  - sudo /etc/init.d/asterisk status || sudo /etc/init.d/asterisk start
  - sudo /etc/init.d/asterisk status || sleep 2
  - vendor/bin/phpunit --coverage-text
