language: php
php:
  - 5.3
  - 5.6
  - hhvm
install:
  - sudo apt-get install -y asterisk
  - export LOGIN='user:pass@localhost'
  - composer install --prefer-source --no-interaction
script:
  - phpunit --coverage-text
